# Generated by Django 3.0.3 on 2020-06-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=234, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Porter', 'Porter'), ('Supervisor', 'Supervisor'), ('Management', 'Management'), ('Admin', 'Admin')], default='Porter', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff_id_number',
            field=models.CharField(default=123456, max_length=10),
            preserve_default=False,
        ),
    ]
