# Generated by Django 3.0.7 on 2020-06-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200611_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_id_number',
            field=models.CharField(max_length=10),
        ),
    ]
