# Generated by Django 3.0.3 on 2020-02-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_num', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('day', models.DateField()),
            ],
        ),
    ]
