# Generated by Django 3.0.3 on 2020-03-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_attendance_examination'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'exam')},
        ),
    ]
