# Generated by Django 3.0.3 on 2020-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
