# Generated by Django 3.0.3 on 2020-04-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20200327_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
