# Generated by Django 3.0.3 on 2020-04-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_visitingstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitingstudent',
            name='phone_number',
        ),
    ]
