# Generated by Django 3.0.3 on 2020-04-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_visitingstudent_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('moving', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('mover', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_properties', to='students.Student')),
            ],
        ),
    ]
