# Generated by Django 3.0.3 on 2020-04-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
