# Generated by Django 3.0.3 on 2020-06-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_property_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='examination',
            name='date',
        ),
    ]
