# Generated by Django 3.0.3 on 2020-06-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20200604_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
