# Generated by Django 3.0.3 on 2020-06-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_attendance_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelattendance',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
