# Generated by Django 3.0.3 on 2020-06-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_supervisorattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porterattendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supervisorattendance',
            options={},
        ),
    ]
