# Generated by Django 3.0.3 on 2020-06-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20200611_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelattendance',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hostelattendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
